#!/usr/bin/env bash
# =============================================================================
# backend.sh - NestJS backend installation for SynapseAnime
# =============================================================================
# Provides: install_backend() which copies sources, generates .env, builds
# the NestJS application, prunes dev dependencies, and sets permissions.
# Sourced by install.sh after common.sh.
# =============================================================================

# ---------------------------------------------------------------------------
# install_backend - Install and build the NestJS backend.
# ---------------------------------------------------------------------------
# Globals used: INSTALL_DIR, SCRIPT_DIR, DB_HOST, DB_PORT, DB_NAME, DB_USER,
#               DB_PASSWORD, REDIS_HOST, REDIS_PORT, REDIS_PASSWORD,
#               JWT_SECRET, JWT_EXPIRES_IN, API_PORT, CORS_ORIGINS,
#               CONSUMET_PORT, MANGAHOOK_PORT, DRY_RUN, UPDATE_MODE
# Side effects: creates system user, copies files, builds app, generates .env
install_backend() {
    log_section "Backend (NestJS)"

    local backend_dir="${INSTALL_DIR}/backend"

    # Create system user if needed
    if ! id -u openanime &>/dev/null; then
        if [[ "$DRY_RUN" == "true" ]]; then
            log_debug "[DRY] Would create system user 'openanime'"
        else
            run_cmd "Creating system user 'openanime'" \
                "useradd --system --shell /usr/sbin/nologin --home-dir ${INSTALL_DIR} --create-home openanime"
        fi
    else
        log_ok "System user 'openanime' already exists"
    fi

    # Determine source directory
    local src_dir
    if [[ "${DEPLOY_SOURCE:-local}" == "git" ]]; then
        src_dir="${INSTALL_DIR}/_src/backend"
    else
        # Local source: resolve relative to SCRIPT_DIR (deploy root -> project root)
        src_dir="$(cd "$SCRIPT_DIR/../.." && pwd)/backend"
    fi

    if [[ ! -d "$src_dir" ]]; then
        log_fail "Backend source directory not found: $src_dir"
        return 1
    fi

    # Copy sources via rsync
    ensure_dir "$backend_dir" "openanime:openanime"

    run_cmd "Syncing backend sources" \
        "rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='mobile' \
            --exclude='.next' \
            --exclude='dist' \
            --exclude='.env' \
            --exclude='video_library' \
            --exclude='scripts' \
            '${src_dir}/' '${backend_dir}/'"

    # Generate .env file (preserve existing values on update)
    _generate_backend_env "$backend_dir"

    # Install dependencies and build
    run_cmd "Installing backend dependencies" \
        "cd '${backend_dir}' && npm install --no-audit --no-fund 2>&1"

    run_cmd "Building NestJS application" \
        "cd '${backend_dir}' && npx nest build 2>&1"

    run_cmd "Pruning dev dependencies" \
        "cd '${backend_dir}' && npm prune --omit=dev 2>&1"

    # Create video_library directory
    ensure_dir "${backend_dir}/video_library" "openanime:openanime"

    # Set permissions
    if [[ "$DRY_RUN" != "true" ]]; then
        chown -R openanime:openanime "$backend_dir"
        log_ok "Backend installed and built at ${backend_dir}"
    fi
}

# ---------------------------------------------------------------------------
# _generate_backend_env DIR - Generate or update backend/.env file.
# ---------------------------------------------------------------------------
# On update: preserves existing values, only adds new keys.
# Arguments:
#   DIR - backend directory path
# Globals used: DB_*, REDIS_*, JWT_*, API_PORT, CORS_ORIGINS, CONSUMET_PORT,
#               MANGAHOOK_PORT, INSTALL_DIR
_generate_backend_env() {
    local dir="$1"
    local env_file="${dir}/.env"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_debug "[DRY] Would generate ${env_file}"
        return 0
    fi

    # On update, preserve existing .env and only add missing keys
    if [[ -f "$env_file" ]] && is_update_mode; then
        log_info "Preserving existing backend .env (update mode)"
        backup_file "$env_file"
        return 0
    fi

    local redis_url="redis://"
    if [[ -n "$REDIS_PASSWORD" ]]; then
        redis_url="redis://:${REDIS_PASSWORD}@"
    fi
    redis_url="${redis_url}${REDIS_HOST}:${REDIS_PORT}"

    cat > "$env_file" <<ENV
# SynapseAnime Backend Environment
# Generated by installer on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Database (TypeORM)
DB_TYPE=postgres
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

# Auto-create schema from entities (needed for first install; safe to leave on
# in single-node deployments. For multi-node or when using migrations, set to
# false and run \`typeorm migration:run\` instead).
DB_SYNCHRONIZE=true

# Redis
REDIS_URL=${redis_url}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}

# Auth
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

# Server
PORT=${API_PORT}
NODE_ENV=production
CORS_ORIGINS=${CORS_ORIGINS}

# External microservices (backend uses *_URL env names)
CONSUMET_API_URL=http://127.0.0.1:${CONSUMET_PORT}
CONSUMET_PROVIDER=animeunity
MANGAHOOK_API_URL=http://127.0.0.1:${MANGAHOOK_PORT}/api

# Third-party APIs (optional — fill in manually)
# JIKAN_API_URL=https://api.jikan.moe/v4
# MANGADEX_API_URL=https://api.mangadex.org
# TMDB_API_KEY=
# PERPLEXITY_API_KEY=
# STRIPE_SECRET_KEY=
# GOOGLE_CLIENT_ID=

# Storage
VIDEO_LIBRARY_PATH=${INSTALL_DIR}/backend/video_library
ENV

    chmod 600 "$env_file"
    chown openanime:openanime "$env_file"
    log_ok "Generated backend .env"
}
