#!/usr/bin/env bash
# =============================================================================
# consumet.sh - Consumet API installation for SynapseAnime
# =============================================================================
# Provides: install_consumet() which copies sources, installs dependencies
# (keeping devDeps for ts-node), generates .env, and sets permissions.
# Sourced by install.sh after common.sh.
# =============================================================================

# ---------------------------------------------------------------------------
# install_consumet - Install the Consumet API service.
# ---------------------------------------------------------------------------
# Globals used: INSTALL_DIR, SCRIPT_DIR, DEPLOY_SOURCE, CONSUMET_PORT, DRY_RUN
# Side effects: copies files, installs npm deps, generates .env
install_consumet() {
    log_section "Consumet API"

    local consumet_dir="${INSTALL_DIR}/consumet-api"

    # Determine source directory
    local src_dir
    if [[ "${DEPLOY_SOURCE:-local}" == "git" ]]; then
        src_dir="${INSTALL_DIR}/_src/consumet-api"
    else
        src_dir="$(cd "$SCRIPT_DIR/../.." && pwd)/consumet-api"
    fi

    if [[ ! -d "$src_dir" ]]; then
        log_fail "Consumet API source directory not found: $src_dir"
        return 1
    fi

    # Copy sources
    ensure_dir "$consumet_dir" "openanime:openanime"

    run_cmd "Syncing Consumet API sources" \
        "rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env' \
            '${src_dir}/' '${consumet_dir}/'"

    # Install dependencies (keep devDeps - needs ts-node)
    run_cmd "Installing Consumet API dependencies" \
        "cd '${consumet_dir}' && npm install --no-audit --no-fund 2>&1"

    # Generate .env
    _generate_consumet_env "$consumet_dir"

    # Set permissions
    if [[ "$DRY_RUN" != "true" ]]; then
        chown -R openanime:openanime "$consumet_dir"
        log_ok "Consumet API installed at ${consumet_dir}"
    fi
}

# ---------------------------------------------------------------------------
# _generate_consumet_env DIR - Generate Consumet API .env file.
# ---------------------------------------------------------------------------
# Arguments:
#   DIR - consumet-api directory path
# Globals used: CONSUMET_PORT
_generate_consumet_env() {
    local dir="$1"
    local env_file="${dir}/.env"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_debug "[DRY] Would generate ${env_file}"
        return 0
    fi

    if [[ -f "$env_file" ]] && is_update_mode; then
        log_info "Preserving existing Consumet .env (update mode)"
        backup_file "$env_file"
        return 0
    fi

    cat > "$env_file" <<ENV
# Consumet API Environment
# Generated by installer on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

PORT=${CONSUMET_PORT}
NODE_ENV=production
ENV

    chmod 600 "$env_file"
    chown openanime:openanime "$env_file"
    log_ok "Generated Consumet API .env"
}
