#!/usr/bin/env bash
# =============================================================================
# mangahook.sh - MangaHook API installation for SynapseAnime
# =============================================================================
# Provides: install_mangahook() which copies sources, installs production
# dependencies, generates .env, and sets permissions.
# Sourced by install.sh after common.sh.
# =============================================================================

# ---------------------------------------------------------------------------
# install_mangahook - Install the MangaHook API service.
# ---------------------------------------------------------------------------
# Globals used: INSTALL_DIR, SCRIPT_DIR, DEPLOY_SOURCE, MANGAHOOK_PORT, DRY_RUN
# Side effects: copies files, installs npm deps, generates .env
install_mangahook() {
    log_section "MangaHook API"

    local mangahook_dir="${INSTALL_DIR}/mangahook-api"

    # Determine source directory
    local src_dir
    if [[ "${DEPLOY_SOURCE:-local}" == "git" ]]; then
        src_dir="${INSTALL_DIR}/_src/mangahook-api"
    else
        src_dir="$(cd "$SCRIPT_DIR/../.." && pwd)/mangahook-api"
    fi

    if [[ ! -d "$src_dir" ]]; then
        log_fail "MangaHook API source directory not found: $src_dir"
        return 1
    fi

    # Copy sources
    ensure_dir "$mangahook_dir" "openanime:openanime"

    run_cmd "Syncing MangaHook API sources" \
        "rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env' \
            '${src_dir}/' '${mangahook_dir}/'"

    # Install production dependencies only (no ts-node needed)
    run_cmd "Installing MangaHook API dependencies" \
        "cd '${mangahook_dir}/server' && npm install --omit=dev --no-audit --no-fund 2>&1"

    # Generate .env
    _generate_mangahook_env "$mangahook_dir"

    # Set permissions
    if [[ "$DRY_RUN" != "true" ]]; then
        chown -R openanime:openanime "$mangahook_dir"
        log_ok "MangaHook API installed at ${mangahook_dir}"
    fi
}

# ---------------------------------------------------------------------------
# _generate_mangahook_env DIR - Generate MangaHook API .env file.
# ---------------------------------------------------------------------------
# Arguments:
#   DIR - mangahook-api directory path
# Globals used: MANGAHOOK_PORT
_generate_mangahook_env() {
    local dir="$1"
    local env_file="${dir}/server/.env"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_debug "[DRY] Would generate ${env_file}"
        return 0
    fi

    if [[ -f "$env_file" ]] && is_update_mode; then
        log_info "Preserving existing MangaHook .env (update mode)"
        backup_file "$env_file"
        return 0
    fi

    cat > "$env_file" <<ENV
# MangaHook API Environment
# Generated by installer on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

PORT=${MANGAHOOK_PORT}
NODE_ENV=production
ENV

    chmod 600 "$env_file"
    chown openanime:openanime "$env_file"
    log_ok "Generated MangaHook API .env"
}
