#!/usr/bin/env bash
# =============================================================================
# web.sh - Next.js web frontend installation for SynapseAnime
# =============================================================================
# Provides: install_web() which copies sources, installs dependencies, builds
# the Next.js application, generates .env, and sets permissions.
# Note: dev dependencies are NOT pruned (typescript required by next start).
# Sourced by install.sh after common.sh.
# =============================================================================

# ---------------------------------------------------------------------------
# install_web - Install and build the Next.js web frontend.
# ---------------------------------------------------------------------------
# Globals used: INSTALL_DIR, SCRIPT_DIR, DEPLOY_SOURCE, NEXT_PUBLIC_API_URL,
#               API_PORT, DOMAIN, WEB_PORT, DRY_RUN, UPDATE_MODE
# Side effects: copies files, builds app, generates .env
install_web() {
    log_section "Web Frontend (Next.js)"

    local web_dir="${INSTALL_DIR}/web"

    # Determine source directory
    local src_dir
    if [[ "${DEPLOY_SOURCE:-local}" == "git" ]]; then
        src_dir="${INSTALL_DIR}/_src/web"
    else
        src_dir="$(cd "$SCRIPT_DIR/../.." && pwd)/web"
    fi

    if [[ ! -d "$src_dir" ]]; then
        log_fail "Web source directory not found: $src_dir"
        return 1
    fi

    # Copy sources via rsync
    ensure_dir "$web_dir" "openanime:openanime"

    run_cmd "Syncing web frontend sources" \
        "rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next' \
            --exclude='.env' \
            --exclude='.env.local' \
            '${src_dir}/' '${web_dir}/'"

    # Install dependencies (keep devDeps - typescript needed by next start)
    run_cmd "Installing web dependencies" \
        "cd '${web_dir}' && npm install --no-audit --no-fund 2>&1"

    # Generate .env BEFORE build — Next.js bakes NEXT_PUBLIC_* vars into
    # the JS bundle at compile time, and reads .env automatically
    _generate_web_env "$web_dir"

    # Build Next.js (reads NEXT_PUBLIC_API_URL from .env just generated)
    run_cmd "Building Next.js application" \
        "cd '${web_dir}' && NEXT_PUBLIC_API_URL='${NEXT_PUBLIC_API_URL}' npx next build 2>&1"

    # Set permissions
    if [[ "$DRY_RUN" != "true" ]]; then
        chown -R openanime:openanime "$web_dir"
        log_ok "Web frontend installed and built at ${web_dir}"
    fi
}

# ---------------------------------------------------------------------------
# _generate_web_env DIR - Generate or update web/.env file.
# ---------------------------------------------------------------------------
# On update: preserves existing .env, only backs up.
# Arguments:
#   DIR - web directory path
# Globals used: NEXT_PUBLIC_API_URL, API_PORT, DOMAIN, WEB_PORT
_generate_web_env() {
    local dir="$1"
    local env_file="${dir}/.env"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_debug "[DRY] Would generate ${env_file}"
        return 0
    fi

    if [[ -f "$env_file" ]] && is_update_mode; then
        log_info "Preserving existing web .env (update mode)"
        backup_file "$env_file"
        return 0
    fi

    cat > "$env_file" <<ENV
# SynapseAnime Web Frontend Environment
# Generated by installer on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
PORT=${WEB_PORT}
NODE_ENV=production
ENV

    chmod 600 "$env_file"
    chown openanime:openanime "$env_file"
    log_ok "Generated web .env"
}
